all: stop_noisy_sender stop_noisy_receiver

stop_noisy_sender: stop_noisy_sender.c 
	gcc stop_noisy_sender.c -o stop_noisy_sender
stop_noisy_receiver: stop_noisy_receiver.c
	gcc stop_noisy_receiver.c -o stop_noisy_receiver
