all: simplest_sender simplest_receiver

simplest_sender: simplest_sender.c
	gcc simplest_sender.c -o simplest_sender

simplest_receiver: simplest_receiver.c
	gcc simplest_receiver.c -o simplest_receiver
