all: stop_noiseless_receiver stop_noiseless_sender

stop_noiseless_receiver: stop_noiseless_receiver.c
	gcc stop_noiseless_receiver.c -o stop_noiseless_receiver

stop_noiseless_sender: stop_noiseless_sender.c
	gcc stop_noiseless_sender.c -o stop_noiseless_sender
